<?php

/**
 * @file
 * acquia_purge_d8cache.module
 */

/**
 * Implements hook_init().
 */
function acquia_purge_d8cache_init() {
  $identifier = _acquia_purge_d8cache_get_site_identifier();
  drupal_add_http_header('X-Acquia-Site', $identifier);
}

/**
 * Implements hook_flush_caches().
 */
function acquia_purge_d8cache_flush_caches() {
  $tags = db_select('d8cache_cache_tags', 'c')
    ->distinct()
    ->fields('c', ['tag'])
    ->execute()
    ->fetchCol();

  // Invalidate all tags when full site cache is cleared.
  acquia_purge_d8cache_invalidate_cache_tags($tags);
}

/**
 * Implements hook_invalidate_cache_tags().
 */
function acquia_purge_d8cache_invalidate_cache_tags($tags) {
  // TODO Call acquia LB to purge varnish.
}

/**
 * Implements hook_views_pre_view().
 */
function acquia_purge_d8cache_views_pre_build(&$view) {
  // Change views cache to none since varnish will do the cacheing for us.
  if ($view->display_handler->get_plugin('cache')->plugin_name == 'time') {
    $view->display_handler->override_option('cache', ['type' => 'none']);
  }
}

function _acquia_purge_d8cache_get_site_identifier() {
  $site_name = _acquia_purge_d8cache_get_site_name();
  $site_path = conf_path();
  return substr(hash('md5', $site_name . $site_path), 0, 16);
}

function _acquia_purge_d8cache_get_balancers() {
  static $balancers;

  // Cache the results statically, preventing multiple lookups during runtime.
  if (is_null($balancers)) {
    $balancers = [];
    foreach (variable_get('reverse_proxies', []) as $ip_address) {
      $balancers[] = $ip_address;
    }
  }
  return $balancers;
}

/**
 * Determine the Acquia site name.
 *
 * @return false|string
 *   Either a boolean FALSE or a string identifying what site we are on.
 */
function _acquia_purge_d8cache_get_site_name() {
  static $ah_site_name;
  if (is_null($ah_site_name)) {
    $ah_site_name = FALSE;
    if (isset($_ENV['AH_SITE_NAME']) && !empty($_ENV['AH_SITE_NAME'])) {
      $ah_site_name = $_ENV['AH_SITE_NAME'];
    }
  }
  return $ah_site_name;
}

/**
 * Determine the Acquia site group.
 *
 * @return false|string
 *   Either a boolean FALSE or a string identifying what site group this is.
 */
function _acquia_purge_d8cache_get_site_group() {
  static $ah_site_group;
  if (is_null($ah_site_group)) {
    $ah_site_group = FALSE;
    if (isset($_ENV['AH_SITE_GROUP']) && !empty($_ENV['AH_SITE_GROUP'])) {
      $ah_site_group = $_ENV['AH_SITE_GROUP'];
    }
  }
  return $ah_site_group;
}

function acquia_purge_d8cache_hosting_info() {
  return [
    'balancer_addresses' => _acquia_purge_d8cache_get_balancers(),
    'site_name' => _acquia_purge_d8cache_get_site_name(),
    'site_group' => _acquia_purge_d8cache_get_site_group(),
  ];
}

/**
 * Invalidate a set of tag invalidations.
 */
function acquia_purge_d8cache_invalidate(array $tags) {

  // Create grouped sets of 12 so that we can spread out the BAN load.
  $group = 0;
  $groups = [];
  foreach ($tags as $tag) {
    if (!isset($groups[$group])) {
      $groups[$group] = ['tags' => [], ['objects' => []]];
    }
    if (count($groups[$group]['tags']) >= 15) {
      $group++;
    }
    $groups[$group]['tags'][] = $tag;
  }

  // Test if we have at least one group of tag(s) to purge, if not, bail.
  if (!count($groups)) {
    return;
  }

  // Now create requests for all groups of tags.
  $site = _acquia_purge_d8cache_get_site_identifier();
  $ipv4_addresses = _acquia_purge_d8cache_get_balancers();

  foreach ($groups as $group_id => $group) {
    $tags = implode(' ', $group['tags']);
    foreach ($ipv4_addresses as $ipv4) {
      yield $group_id => function ($poolopt) use ($site, $tags, $ipv4) {
        $opt = [
          'headers' => [
            'X-Acquia-Purge' => $site,
            'X-Acquia-Purge-Tags' => $tags,
            'Accept-Encoding' => 'gzip',
            'User-Agent' => 'Acquia Purge',
          ],
        ];
        if (is_array($poolopt) && count($poolopt)) {
          $opt = array_merge($poolopt, $opt);
        }

        //        return $this->client->requestAsync('BAN', "http://$ipv4/tags", $opt);
      };
    }
  }
}
